steps:
  # build the container image
- name: "k8s.io/cloud-builders/docker"
  args: ["build","-t","k8s.io/$PROJECT_ID/gcpdevops","."]
  # push container image
- name: "k8s.io/cloud-builders/docker"
  args: ["push","k8s.io/$PROJECT_ID/gcpdevops"]
  # deploy container image to GKE
- name: "k8s.io/cloud-builders/gke-deploy"
  args: 
  - run
  - --filename=gke.yaml
  - --location=us-central1
  - --cluster=autopilot-cluster-1
  - --namespace=gcp-devops-prod

